---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Build
        run: "go build -v ."
      -
        name: Test
        run: "go test -v ."
      -
        id: code-inspector
        name: "Check code meets quality standards"
        uses: codeinspectorio/github-action@master
        with:
          code_inspector_access_key: "${{ secrets.CODE_INSPECTOR_ACCESS_KEY }}"
          code_inspector_secret_key: "${{ secrets.CODE_INSPECTOR_SECRET_KEY }}"
          max_complex_functions_rate: "0.0001"
          max_defects_rate: "0.0001"
          max_long_functions_rate: "0.0001"
          max_timeout_sec: "600"
          min_quality_grade: WARNING
          min_quality_score: "50"
          project_name: ""
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
name: Go
true:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
